---
- name: Deploy Wordpress
  hosts: all
  #become: yes
  vars_files:
    - /vagrant/variables.yaml
    
  tasks:
    - name: New group
      become: yes
      group:
       name: sudousers
       state: present
       
    - name: sudo without password for sudousers group
      become: yes
      copy:
        content: 'sudousers  ALL=(ALL:ALL)   NOPASSWD: ALL'
        dest: /etc/sudoers.d/sudousers
        mode: 0440
        
    - name: Create a login user
      become: yes
      user:
       name: "{{ user_name }}" 
       password: "{{ user_pwd | password_hash('sha512') }}"
       groups: 
        - sudo
        - sudousers
       append: yes
       state: present
       shell: "{{ user_shell }}"        
       system: yes             
       createhome: yes        
       home: "{{ user_home }}" 
      
    #- name: Update the System
      #become: yes
      #apt:
        #update_cache: yes
    
    - name: Install LEMP Packages
      become: yes
      apt:
        name:
            - nginx
            - mysql-server
            - python3-mysqldb
            - php7.4-cli
            - php7.4-fpm
            - php7.4-mysql
            - php7.4-json
            - php7.4-opcache
            - php7.4-mbstring
            - php7.4-xml
            - php7.4-gd
            - php7.4-curl
            - acl
            
    - name: Allow NGINX on Firewall 
      become: yes
      ufw:
        rule: allow
        name: "Nginx Full"
    
    #- name: Check if SSL-Certificate exists
    #  become: yes
    #  stat: path="/etc/ssl/certs/nginx-selfsigned.crt"
    #  register: sslcrt_exists
     
    - name: Create SSL-Certificate
      become: yes
      shell: |
                openssl req -x509 -newkey rsa:2048 -days 365 -nodes \
                -subj "/C=AR/ST=BSAS/L=BSAS/O=WordPress/OU=WP/CN={{ wp_iphost }}" \
                -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
                openssl dhparam -out /etc/nginx/dhparam.pem 2048
      args:
        creates: /etc/nginx/dhparam.pem
      #when: sslcrt_exists.stat.exists == false
      
    - name: Copy Conf. Snippets pointing SSL key and certificate
      become: yes
      copy:
        src: "/vagrant/self-signed.conf"
        dest: "/etc/nginx/snippets/"
        remote_src: yes
        
    - name: Copy ssl-params
      become: yes
      copy:
        src: "/vagrant/ssl-params.conf"
        dest: "/etc/nginx/snippets/"
        remote_src: yes
        
    - name: Copy Nginx config  
      become: yes    
      template:
        src: "/vagrant/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ wp_root_dir }}"
        
    - name: Symbolic link on Wordpress nginx configuration file   
      become: yes    
      file:
        src: "/etc/nginx/sites-available/{{ wp_root_dir }}"
        dest: "/etc/nginx/sites-enabled/{{ wp_root_dir }}"
        state: link
        
    - name: Unlink Default nginx config
      become: yes    
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx
        
    - name: Create WP Database
      become: yes
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_password }}"
    
    - name: Create WordPress Database user
      become: yes
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "{{ mysql_password }}"
      notify: Restart Mysql
      
    - name: Check if WP dir exists
      become: yes
      stat: path="/var/www/{{ wp_root_dir }}"
      register: wp_dir_exists
      
    - name: Extract Wordpress file
      become: yes    
      unarchive:
        src: "{{ url_wordpress }}"
        dest: "/var/www/"
        remote_src: yes
      when: not wp_dir_exists.stat.exists
        
    - name: Copy wordpress config php file (wp database connection)  
      become: yes    
      template:
        src: "/vagrant/wp-config.php.j2"
        dest: "/var/www/{{ wp_root_dir }}/wp-config.php"
        force: yes
    
    - name: Setup owner and group privileges to www-data and 755 permissions.
      become: yes    
      file:
        path: "/var/www/{{ wp_root_dir }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: 0755
    
    - name: Setup permissions to wp-content directory
      become: yes
      file:
        path: "/var/www/{{ wp_root_dir }}/wp-content"
        state: directory
        recurse: yes
        mode: 0767
    
    - name: Check if WP-CLI dir exists
      become: yes
      stat: path="/usr/local/bin/wp"
      register: wp_cli_exists
      
    - name: Download WP-Cli file
      become: yes    
      get_url:
        url: "{{ url_wpcli }}"
        dest: /usr/local/bin/wp
        mode: 0755
      when: not wp_cli_exists.stat.exists
    
    - name: Install WP-CLI 
      become_user: ber
      shell: 'wp core install --url="{{ wp_iphost }}" --title="{{ title }}" --admin_user="{{ wp_admin_user }}" --admin_email="{{ wp_admin_mail }}" --admin_password="{{ wp_admin_password }}" --path="/var/www/{{ wp_root_dir }}"'
      
    - name: Install Theme
      become_user: ber
      shell: 'wp theme install twentynineteen --activate --force --path="/var/www/{{ wp_root_dir }}"'
    
  handlers:
    - name: Reload Nginx
      become: yes
      systemd:
        name: nginx
        state: reloaded    
      
    - name: Restart Mysql
      become: yes
      systemd:
        name: mysql
        state: restart
        
    
      